#!/usr/bin/env python3
"""Helpers for the code-project-guidance-map skill."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


START_MARKER = "<!-- code-project-guidance-map:start -->"
END_MARKER = "<!-- code-project-guidance-map:end -->"
GENERATOR = "code-project-guidance-map"
SIGNATURE_ALGORITHM = "sha256:v1"
GENERATED_AT_RE = re.compile(r"^Generated at:\s*(?P<value>.+?)\s*$", re.MULTILINE)
GENERATOR_RE = re.compile(r"^Generator:\s*(?P<value>.+?)\s*$", re.MULTILINE)
LEGACY_GENERATED_BY_RE = re.compile(r"^Generated by:\s*(?P<value>.+?)\s*$", re.MULTILINE)
GIT_BASELINE_RE = re.compile(r"^Git baseline:\s*(?P<value>.+?)\s*$", re.MULTILINE)
SIGNATURE_ALGORITHM_RE = re.compile(r"^Signature algorithm:\s*(?P<value>.+?)\s*$", re.MULTILINE)
SIGNATURE_RE = re.compile(r"^Signature:\s*(?P<value>.+?)\s*$", re.MULTILINE)


class GuidanceMapError(RuntimeError):
    """Raised for user-fixable guidance map errors."""


def run_git(repo: Path, args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def repo_root(start: Path) -> tuple[Path, bool]:
    result = run_git(start, ["rev-parse", "--show-toplevel"])
    if result.returncode == 0:
        return Path(result.stdout.strip()).resolve(), True
    return start.resolve(), False


def current_head(repo: Path, git_available: bool) -> str:
    if not git_available:
        return "none"
    result = run_git(repo, ["rev-parse", "--short", "HEAD"])
    if result.returncode != 0:
        return "none"
    value = result.stdout.strip()
    return value or "none"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def find_block(text: str) -> tuple[int, int, str] | None:
    start_count = text.count(START_MARKER)
    end_count = text.count(END_MARKER)
    if start_count == 0 and end_count == 0:
        return None
    if start_count != 1 or end_count != 1:
        raise GuidanceMapError("Malformed guidance block markers: expected exactly one start and one end marker.")
    start = text.index(START_MARKER)
    end_marker_start = text.index(END_MARKER)
    if end_marker_start < start:
        raise GuidanceMapError("Malformed guidance block markers: end marker appears before start marker.")
    end = end_marker_start + len(END_MARKER)
    return start, end, text[start:end]


def metadata_value(pattern: re.Pattern[str], block: str | None) -> str | None:
    if not block:
        return None
    match = pattern.search(block)
    if not match:
        return None
    return match.group("value").strip()


def parse_iso_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    normalized = value.strip()
    if normalized.endswith("Z"):
        normalized = f"{normalized[:-1]}+00:00"
    try:
        parsed = datetime.fromisoformat(normalized)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def unique_ordered(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        value = value.strip().replace("\\", "/")
        if not value or value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def git_files(repo: Path, args: list[str]) -> list[str]:
    result = run_git(repo, args)
    if result.returncode != 0:
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def changed_files(repo: Path, git_available: bool, since: datetime | None) -> dict[str, list[str]]:
    if not git_available:
        return {
            "committed": [],
            "staged": [],
            "unstaged": [],
            "untracked": [],
            "all": [],
        }

    committed: list[str] = []
    if since is not None:
        since_arg = since.strftime("%Y-%m-%d %H:%M:%S %z")
        committed = git_files(repo, ["log", f"--since={since_arg}", "--name-only", "--pretty=format:"])

    staged = git_files(repo, ["diff", "--name-only", "--cached"])
    unstaged = git_files(repo, ["diff", "--name-only"])
    untracked = git_files(repo, ["ls-files", "--others", "--exclude-standard"])
    all_files = unique_ordered([*committed, *staged, *unstaged, *untracked])

    return {
        "committed": unique_ordered(committed),
        "staged": unique_ordered(staged),
        "unstaged": unique_ordered(unstaged),
        "untracked": unique_ordered(untracked),
        "all": all_files,
    }


def signature_payload(generator: str, timestamp: str, baseline: str, guidance: str) -> str:
    return "\n".join(
        [
            f"generator={generator}",
            f"generated_at={timestamp}",
            f"git_baseline={baseline}",
            f"guidance={guidance.strip()}",
        ]
    )


def compute_signature(generator: str, timestamp: str, baseline: str, guidance: str) -> str:
    payload = signature_payload(generator, timestamp, baseline, guidance)
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


def guidance_body_from_block(block: str) -> str | None:
    lines = block.splitlines()
    signature_index = next((index for index, line in enumerate(lines) if line.startswith("Signature:")), None)
    if signature_index is None:
        return None

    body_start = signature_index + 1
    if body_start < len(lines) and not lines[body_start].strip():
        body_start += 1

    body_end = len(lines)
    if lines and lines[-1].strip() == END_MARKER:
        body_end -= 1

    guidance = "\n".join(lines[body_start:body_end]).strip()
    return guidance or None


def signature_is_valid(
    block: str | None,
    generator: str | None,
    timestamp: str | None,
    baseline: str | None,
    algorithm: str | None,
    signature: str | None,
) -> bool:
    if not block or not generator or not timestamp or baseline is None or not algorithm or not signature:
        return False
    if algorithm != SIGNATURE_ALGORITHM or not signature.startswith("sha256:"):
        return False
    guidance = guidance_body_from_block(block)
    if guidance is None:
        return False
    expected = compute_signature(generator, timestamp, baseline, guidance)
    return signature == expected


def render_block(guidance: str, timestamp: str, baseline: str) -> str:
    if START_MARKER in guidance or END_MARKER in guidance:
        raise GuidanceMapError("Guidance content must not contain guidance block markers.")
    guidance = guidance.strip()
    if not guidance:
        raise GuidanceMapError("Guidance content is empty.")
    signature = compute_signature(GENERATOR, timestamp, baseline, guidance)
    return "\n".join(
        [
            START_MARKER,
            "## Code Project Guidance Map",
            "",
            f"Generator: {GENERATOR}",
            f"Generated at: {timestamp}",
            f"Git baseline: {baseline}",
            f"Signature algorithm: {SIGNATURE_ALGORITHM}",
            f"Signature: {signature}",
            "",
            guidance,
            END_MARKER,
            "",
        ]
    )


def update_agents_text(existing: str, block: str) -> str:
    found = find_block(existing)
    if found is None:
        prefix = existing.rstrip()
        if prefix:
            return f"{prefix}\n\n{block}"
        return block
    start, end, _ = found
    before = existing[:start].rstrip()
    after = existing[end:].lstrip()
    pieces = []
    if before:
        pieces.append(before)
    pieces.append(block.rstrip())
    if after:
        pieces.append(after.rstrip())
    return "\n\n".join(pieces) + "\n"


def status(repo_arg: Path) -> dict[str, object]:
    root, git_available = repo_root(repo_arg)
    agents_path = root / "AGENTS.md"
    exists = agents_path.exists()
    text = read_text(agents_path) if exists else ""
    block_info = find_block(text) if exists else None
    block = block_info[2] if block_info else None
    generated_at = metadata_value(GENERATED_AT_RE, block)
    generator = metadata_value(GENERATOR_RE, block)
    legacy_generated_by = metadata_value(LEGACY_GENERATED_BY_RE, block)
    git_baseline = metadata_value(GIT_BASELINE_RE, block)
    signature_algorithm = metadata_value(SIGNATURE_ALGORITHM_RE, block)
    signature = metadata_value(SIGNATURE_RE, block)
    parsed_generated_at = parse_iso_datetime(generated_at)
    has_block = block is not None
    generated_at_valid = (not has_block and generated_at is None) or parsed_generated_at is not None
    signature_valid = (
        signature_is_valid(block, generator, generated_at, git_baseline, signature_algorithm, signature)
        if has_block
        else None
    )
    changes = changed_files(root, git_available, parsed_generated_at)

    return {
        "repo_root": str(root),
        "agents_path": str(agents_path),
        "agents_exists": exists,
        "has_block": has_block,
        "generator": generator,
        "generated_by": legacy_generated_by,
        "generated_at": generated_at,
        "generated_at_valid": generated_at_valid,
        "git_baseline": git_baseline,
        "signature_algorithm": signature_algorithm,
        "signature": signature,
        "signature_valid": signature_valid,
        "git_available": git_available,
        "current_head": current_head(root, git_available),
        "changed_files": changes["all"],
        "changed_files_by_source": changes,
        "requires_full_read": (not has_block) or (has_block and (not generated_at_valid or not signature_valid)),
    }


def update(repo_arg: Path, guidance_file: Path, timestamp: str | None) -> dict[str, object]:
    root, git_available = repo_root(repo_arg)
    agents_path = root / "AGENTS.md"
    guidance = read_text(guidance_file)
    timestamp = timestamp or datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    baseline = current_head(root, git_available)
    block = render_block(guidance, timestamp, baseline)
    existing = read_text(agents_path) if agents_path.exists() else ""
    updated = update_agents_text(existing, block)
    write_text(agents_path, updated)
    return {
        "repo_root": str(root),
        "agents_path": str(agents_path),
        "has_block": True,
        "generated_at": timestamp,
        "git_baseline": baseline,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Manage the AGENTS.md guidance map block.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    status_parser = subparsers.add_parser("status", help="Inspect AGENTS.md and Git delta state.")
    status_parser.add_argument("--repo", default=".", help="Repository or project directory.")

    update_parser = subparsers.add_parser("update", help="Create or replace the guidance block.")
    update_parser.add_argument("--repo", default=".", help="Repository or project directory.")
    update_parser.add_argument("--guidance-file", required=True, help="Markdown file containing module entries.")
    update_parser.add_argument("--timestamp", help="ISO-8601 timestamp override for tests.")

    args = parser.parse_args()
    try:
        if args.command == "status":
            output = status(Path(args.repo))
        else:
            output = update(Path(args.repo), Path(args.guidance_file), args.timestamp)
    except GuidanceMapError as exc:
        print(json.dumps({"error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 2

    print(json.dumps(output, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
