#!/usr/bin/env python3
"""Tests for guidance_map.py."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import guidance_map


class GuidanceMapTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.repo = Path(self.tmp.name)

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def write_guidance(self, text: str = "### app\n\n- Module Capability: A\n- Module Responsibility: B\n- Module Structure: C\n") -> Path:
        path = self.repo / "guidance.md"
        path.write_text(text, encoding="utf-8")
        return path

    def test_update_creates_agents_when_missing(self) -> None:
        result = guidance_map.update(self.repo, self.write_guidance(), "2026-01-01T00:00:00Z")
        text = (self.repo / "AGENTS.md").read_text(encoding="utf-8")
        self.assertTrue(result["has_block"])
        self.assertIn(guidance_map.START_MARKER, text)
        self.assertIn("Generated by: code-project-guidance-map skill", text)
        self.assertIn("- Module Capability: A", text)

    def test_update_appends_block_when_agents_has_no_block(self) -> None:
        (self.repo / "AGENTS.md").write_text("# Existing\n\nKeep this.\n", encoding="utf-8")
        guidance_map.update(self.repo, self.write_guidance(), "2026-01-01T00:00:00Z")
        text = (self.repo / "AGENTS.md").read_text(encoding="utf-8")
        self.assertTrue(text.startswith("# Existing\n\nKeep this."))
        self.assertIn(guidance_map.START_MARKER, text)

    def test_update_replaces_block_and_preserves_outside_content(self) -> None:
        old_block = guidance_map.render_block("old", "2025-01-01T00:00:00Z", "abc123")
        (self.repo / "AGENTS.md").write_text(f"before\n\n{old_block}\nafter\n", encoding="utf-8")
        guidance_map.update(self.repo, self.write_guidance("new"), "2026-01-01T00:00:00Z")
        text = (self.repo / "AGENTS.md").read_text(encoding="utf-8")
        self.assertIn("before", text)
        self.assertIn("after", text)
        self.assertIn("new", text)
        self.assertNotIn("old", text)
        self.assertEqual(text.count(guidance_map.START_MARKER), 1)

    def test_status_reports_invalid_signature_time(self) -> None:
        block = guidance_map.render_block("body", "2026-01-01T00:00:00Z", "abc123")
        block = block.replace("Generated at: 2026-01-01T00:00:00Z", "Generated at: not-a-date")
        (self.repo / "AGENTS.md").write_text(block, encoding="utf-8")
        result = guidance_map.status(self.repo)
        self.assertTrue(result["has_block"])
        self.assertFalse(result["generated_at_valid"])
        self.assertTrue(result["requires_full_read"])

    def test_status_handles_non_git_project(self) -> None:
        result = guidance_map.status(self.repo)
        self.assertFalse(result["git_available"])
        self.assertEqual(result["current_head"], "none")
        self.assertEqual(result["changed_files"], [])

    def test_malformed_markers_raise(self) -> None:
        text = f"{guidance_map.START_MARKER}\nmissing end"
        with self.assertRaises(guidance_map.GuidanceMapError):
            guidance_map.find_block(text)


@unittest.skipIf(shutil.which("git") is None, "git is not installed")
class GuidanceMapGitTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.repo = Path(self.tmp.name)
        self.git("init")
        self.git("config", "user.email", "test@example.com")
        self.git("config", "user.name", "Test User")
        (self.repo / "committed.txt").write_text("initial\n", encoding="utf-8")
        self.git("add", "committed.txt")
        self.git("commit", "-m", "initial")

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def git(self, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["git", "-C", str(self.repo), *args],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True,
        )

    def test_changed_files_include_committed_staged_unstaged_and_untracked(self) -> None:
        (self.repo / "new_commit.txt").write_text("new\n", encoding="utf-8")
        self.git("add", "new_commit.txt")
        self.git("commit", "-m", "new commit")
        (self.repo / "staged.txt").write_text("staged\n", encoding="utf-8")
        self.git("add", "staged.txt")
        (self.repo / "committed.txt").write_text("changed\n", encoding="utf-8")
        (self.repo / "untracked.txt").write_text("untracked\n", encoding="utf-8")

        block = guidance_map.render_block("body", "2000-01-01T00:00:00Z", "abc123")
        (self.repo / "AGENTS.md").write_text(block, encoding="utf-8")
        result = guidance_map.status(self.repo)

        changed = set(result["changed_files"])
        self.assertIn("new_commit.txt", changed)
        self.assertIn("staged.txt", changed)
        self.assertIn("committed.txt", changed)
        self.assertIn("untracked.txt", changed)

    def test_clean_repo_with_later_timestamp_has_no_changes(self) -> None:
        block = guidance_map.render_block("body", "2030-01-01T00:00:00Z", "abc123")
        (self.repo / "AGENTS.md").write_text(block, encoding="utf-8")
        self.git("add", "AGENTS.md")
        self.git("commit", "-m", "guide")
        result = guidance_map.status(self.repo)
        self.assertEqual(result["changed_files"], [])


class GuidanceMapCliTests(unittest.TestCase):
    def test_status_cli_outputs_json(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            script = Path(guidance_map.__file__).resolve()
            result = subprocess.run(
                [sys.executable, str(script), "status", "--repo", tmp],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=True,
            )
            parsed = json.loads(result.stdout)
            self.assertIn("repo_root", parsed)


if __name__ == "__main__":
    unittest.main()
