#!/usr/bin/env python3
"""Helpers for the code-project-guidance-map skill."""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import hmac
import json
import os
import re
import secrets
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


START_MARKER = "<!-- code-project-guidance-map:start -->"
END_MARKER = "<!-- code-project-guidance-map:end -->"
GENERATOR = "code-project-guidance-map"
GUIDE_FORMAT = "action-map:v2"
SIGNATURE_ALGORITHM = "hmac-sha256:v2"
SIGNATURE_SECRET_ENV = "CODE_PROJECT_GUIDANCE_MAP_SECRET"
SIGNATURE_KEY_FILE_ENV = "CODE_PROJECT_GUIDANCE_MAP_KEY_FILE"
SIGNATURE_KEY_HOME_ENV = "CODE_PROJECT_GUIDANCE_MAP_KEY_HOME"
GENERATED_AT_RE = re.compile(r"^Generated at:\s*(?P<value>.+?)\s*$", re.MULTILINE)
GENERATOR_RE = re.compile(r"^Generator:\s*(?P<value>.+?)\s*$", re.MULTILINE)
LEGACY_GENERATED_BY_RE = re.compile(r"^Generated by:\s*(?P<value>.+?)\s*$", re.MULTILINE)
GUIDE_FORMAT_RE = re.compile(r"^Guide format:\s*(?P<value>.+?)\s*$", re.MULTILINE)
GIT_BASELINE_RE = re.compile(r"^Git baseline:\s*(?P<value>.+?)\s*$", re.MULTILINE)
SIGNATURE_KEY_ID_RE = re.compile(r"^Signature key id:\s*(?P<value>.+?)\s*$", re.MULTILINE)
SIGNATURE_ALGORITHM_RE = re.compile(r"^Signature algorithm:\s*(?P<value>.+?)\s*$", re.MULTILINE)
SIGNATURE_RE = re.compile(r"^Signature:\s*(?P<value>.+?)\s*$", re.MULTILINE)
SECTION_HEADING_RE = re.compile(r"^### (?!#)(?P<title>.+?)\s*$", re.MULTILINE)
MODULE_HEADING_RE = re.compile(r"^#### (?!#)(?P<title>.+?)\s*$", re.MULTILINE)
REQUIRED_GUIDE_SECTIONS = (
    "Agent Editing Rules",
    "Task Routing",
    "Module Dependency Rules",
    "Module Map",
)
REQUIRED_MODULE_FIELDS = (
    "Module Path",
    "Owns",
    "Change here when",
    "Do not put here",
    "Key entry points",
)

BOUNDARY_SENSITIVE_PATTERNS = (
    "pom.xml",
    "**/pom.xml",
    "build.gradle",
    "**/build.gradle",
    "build.gradle.kts",
    "**/build.gradle.kts",
    "settings.gradle",
    "**/settings.gradle",
    "settings.gradle.kts",
    "**/settings.gradle.kts",
    "package.json",
    "**/package.json",
    "pnpm-workspace.yaml",
    "tsconfig.json",
    "**/tsconfig.json",
    "vite.config.*",
    "**/vite.config.*",
    "webpack.config.*",
    "**/webpack.config.*",
    "pyproject.toml",
    "requirements*.txt",
    "go.mod",
    "Cargo.toml",
    "*.sln",
    "*.csproj",
    "**/*.csproj",
)
TASK_ROUTING_PATTERNS = (
    "**/controller/**",
    "**/controllers/**",
    "**/routes/**",
    "**/api/**",
    "**/service/**",
    "**/services/**",
    "**/dao/**",
    "**/repository/**",
    "**/repositories/**",
    "**/resources/mappings/**",
    "**/mapper/**",
    "**/mappers/**",
    "**/job/**",
    "**/jobs/**",
    "**/task/**",
    "**/tasks/**",
    "**/schedule/**",
    "**/scheduler/**",
    "**/websocket/**",
    "**/mq/**",
    "**/queue/**",
    "**/*Controller.*",
    "**/*Service.*",
    "**/*Dao.*",
    "**/*DAO.*",
    "**/*Mapper.*",
    "**/*Repository.*",
    "**/*Job.*",
    "**/*Task.*",
    "**/*Scheduler.*",
)
CODE_PATTERNS = (
    "*.java",
    "*.kt",
    "*.ts",
    "*.tsx",
    "*.js",
    "*.jsx",
    "*.py",
    "*.go",
    "*.rs",
    "*.cs",
    "*.php",
    "*.rb",
    "*.sql",
    "*.xml",
    "*.yaml",
    "*.yml",
)
DOCS_PATTERNS = (
    "*.md",
    "README*",
    "LICENSE",
    "docs/**",
    ".github/**",
)


class GuidanceMapError(RuntimeError):
    """Raised for user-fixable guidance map errors."""


def run_git(repo: Path, args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def repo_root(start: Path) -> tuple[Path, bool]:
    result = run_git(start, ["rev-parse", "--show-toplevel"])
    if result.returncode == 0:
        return Path(result.stdout.strip()).resolve(), True
    return start.resolve(), False


def current_head(repo: Path, git_available: bool) -> str:
    if not git_available:
        return "none"
    result = run_git(repo, ["rev-parse", "--short", "HEAD"])
    if result.returncode != 0:
        return "none"
    value = result.stdout.strip()
    return value or "none"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def find_block(text: str) -> tuple[int, int, str] | None:
    start_count = text.count(START_MARKER)
    end_count = text.count(END_MARKER)
    if start_count == 0 and end_count == 0:
        return None
    if start_count != 1 or end_count != 1:
        raise GuidanceMapError("Malformed guidance block markers: expected exactly one start and one end marker.")
    start = text.index(START_MARKER)
    end_marker_start = text.index(END_MARKER)
    if end_marker_start < start:
        raise GuidanceMapError("Malformed guidance block markers: end marker appears before start marker.")
    end = end_marker_start + len(END_MARKER)
    return start, end, text[start:end]


def metadata_value(pattern: re.Pattern[str], block: str | None) -> str | None:
    if not block:
        return None
    match = pattern.search(block)
    if not match:
        return None
    return match.group("value").strip()


def parse_iso_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    normalized = value.strip()
    if normalized.endswith("Z"):
        normalized = f"{normalized[:-1]}+00:00"
    try:
        parsed = datetime.fromisoformat(normalized)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def unique_ordered(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        value = value.strip().replace("\\", "/")
        if not value or value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def matches_any(path: str, patterns: Iterable[str]) -> bool:
    normalized = path.strip().replace("\\", "/")
    return any(fnmatch.fnmatchcase(normalized, pattern) for pattern in patterns)


def classify_changed_files(files: Iterable[str]) -> dict[str, list[str]]:
    impact = {
        "boundary_rules": [],
        "task_routing": [],
        "module_internal": [],
        "docs_only": [],
        "other": [],
    }
    for file in unique_ordered(files):
        if matches_any(file, BOUNDARY_SENSITIVE_PATTERNS):
            impact["boundary_rules"].append(file)
        elif matches_any(file, TASK_ROUTING_PATTERNS):
            impact["task_routing"].append(file)
        elif matches_any(file, DOCS_PATTERNS):
            impact["docs_only"].append(file)
        elif matches_any(file, CODE_PATTERNS):
            impact["module_internal"].append(file)
        else:
            impact["other"].append(file)
    return impact


def git_files(repo: Path, args: list[str]) -> list[str]:
    result = run_git(repo, args)
    if result.returncode != 0:
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def changed_files(repo: Path, git_available: bool, since: datetime | None) -> dict[str, list[str]]:
    if not git_available:
        return {
            "committed": [],
            "staged": [],
            "unstaged": [],
            "untracked": [],
            "all": [],
        }

    committed: list[str] = []
    if since is not None:
        since_arg = since.strftime("%Y-%m-%d %H:%M:%S %z")
        committed = git_files(repo, ["log", f"--since={since_arg}", "--name-only", "--pretty=format:"])

    staged = git_files(repo, ["diff", "--name-only", "--cached"])
    unstaged = git_files(repo, ["diff", "--name-only"])
    untracked = git_files(repo, ["ls-files", "--others", "--exclude-standard"])
    all_files = unique_ordered([*committed, *staged, *unstaged, *untracked])

    return {
        "committed": unique_ordered(committed),
        "staged": unique_ordered(staged),
        "unstaged": unique_ordered(unstaged),
        "untracked": unique_ordered(untracked),
        "all": all_files,
    }


def repo_identity(repo: Path, git_available: bool) -> str:
    if git_available:
        remote = run_git(repo, ["config", "--get", "remote.origin.url"])
        if remote.returncode == 0 and remote.stdout.strip():
            return f"git:{remote.stdout.strip()}"
    return f"path:{repo.resolve()}"


def default_signature_key_id(repo: Path, git_available: bool) -> str:
    digest = hashlib.sha256(repo_identity(repo, git_available).encode("utf-8")).hexdigest()
    return f"repo:{digest[:16]}"


def codex_home() -> Path:
    configured = os.environ.get("CODEX_HOME")
    if configured:
        return Path(configured).expanduser()
    return Path.home() / ".codex"


def signature_key_path(key_id: str) -> Path:
    key_home = os.environ.get(SIGNATURE_KEY_HOME_ENV)
    root = Path(key_home).expanduser() if key_home else codex_home() / "code-project-guidance-map" / "keys"
    safe_key_id = re.sub(r"[^A-Za-z0-9_.-]+", "_", key_id)
    return root / f"{safe_key_id}.key"


def normalize_secret(raw: str) -> bytes:
    value = raw.strip()
    if re.fullmatch(r"[0-9a-fA-F]{64}", value):
        return bytes.fromhex(value)
    return value.encode("utf-8")


def load_signature_secret(key_id: str | None, create: bool) -> tuple[bytes | None, bool, str | None]:
    env_secret = os.environ.get(SIGNATURE_SECRET_ENV)
    if env_secret:
        return normalize_secret(env_secret), True, SIGNATURE_SECRET_ENV

    key_file_env = os.environ.get(SIGNATURE_KEY_FILE_ENV)
    if key_file_env:
        path = Path(key_file_env).expanduser()
    elif key_id:
        path = signature_key_path(key_id)
    else:
        return None, False, None

    if path.exists():
        return normalize_secret(read_text(path)), True, str(path)
    if not create:
        return None, False, str(path)

    path.parent.mkdir(parents=True, exist_ok=True)
    secret = secrets.token_hex(32)
    write_text(path, f"{secret}\n")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    return bytes.fromhex(secret), True, str(path)


def signature_payload(
    generator: str,
    guide_format: str,
    timestamp: str,
    baseline: str,
    algorithm: str,
    key_id: str,
    guidance: str,
) -> str:
    return "\n".join(
        [
            f"generator={generator}",
            f"guide_format={guide_format}",
            f"generated_at={timestamp}",
            f"git_baseline={baseline}",
            f"signature_algorithm={algorithm}",
            f"signature_key_id={key_id}",
            f"guidance={guidance.strip()}",
        ]
    )


def compute_signature(
    secret: bytes,
    generator: str,
    guide_format: str,
    timestamp: str,
    baseline: str,
    algorithm: str,
    key_id: str,
    guidance: str,
) -> str:
    payload = signature_payload(generator, guide_format, timestamp, baseline, algorithm, key_id, guidance)
    digest = hmac.new(secret, payload.encode("utf-8"), hashlib.sha256).hexdigest()
    return f"hmac-sha256:{digest}"


def guidance_body_from_block(block: str) -> str | None:
    lines = block.splitlines()
    signature_index = next((index for index, line in enumerate(lines) if line.startswith("Signature:")), None)
    if signature_index is None:
        return None

    body_start = signature_index + 1
    if body_start < len(lines) and not lines[body_start].strip():
        body_start += 1

    body_end = len(lines)
    if lines and lines[-1].strip() == END_MARKER:
        body_end -= 1

    guidance = "\n".join(lines[body_start:body_end]).strip()
    return guidance or None


def signature_is_valid(
    block: str | None,
    generator: str | None,
    guide_format: str | None,
    timestamp: str | None,
    baseline: str | None,
    algorithm: str | None,
    key_id: str | None,
    signature: str | None,
    secret: bytes | None,
) -> bool:
    if (
        not block
        or not generator
        or not guide_format
        or not timestamp
        or baseline is None
        or not algorithm
        or not key_id
        or not signature
        or secret is None
    ):
        return False
    if guide_format != GUIDE_FORMAT or algorithm != SIGNATURE_ALGORITHM or not signature.startswith("hmac-sha256:"):
        return False
    guidance = guidance_body_from_block(block)
    if guidance is None:
        return False
    expected = compute_signature(secret, generator, guide_format, timestamp, baseline, algorithm, key_id, guidance)
    return hmac.compare_digest(signature, expected)


def top_level_section_body(guidance: str, title: str) -> str | None:
    matches = list(SECTION_HEADING_RE.finditer(guidance))
    for index, match in enumerate(matches):
        if match.group("title").strip() != title:
            continue
        end = matches[index + 1].start() if index + 1 < len(matches) else len(guidance)
        return guidance[match.end() : end].strip()
    return None


def module_entries(module_map_body: str) -> list[tuple[str, str]]:
    matches = list(MODULE_HEADING_RE.finditer(module_map_body))
    entries: list[tuple[str, str]] = []
    for index, match in enumerate(matches):
        title = match.group("title").strip()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(module_map_body)
        entries.append((title, module_map_body[match.end() : end].strip()))
    return entries


def validate_guidance_shape(guidance: str) -> None:
    stripped = guidance.strip()
    if not stripped:
        raise GuidanceMapError("Guidance content is empty.")
    section_positions: list[int] = []
    for section in REQUIRED_GUIDE_SECTIONS:
        match = re.search(rf"^### {re.escape(section)}\s*$", stripped, re.MULTILINE)
        if match is None:
            raise GuidanceMapError(f"Guidance content is missing required section: {section}.")
        section_positions.append(match.start())
    if section_positions != sorted(section_positions):
        raise GuidanceMapError(
            "Guidance sections must be ordered as: "
            + ", ".join(REQUIRED_GUIDE_SECTIONS)
            + "."
        )

    editing_rules = top_level_section_body(stripped, "Agent Editing Rules") or ""
    if not re.search(r"^- \[(MUST|SHOULD|AVOID)\]\s+\S", editing_rules, re.MULTILINE):
        raise GuidanceMapError("Agent Editing Rules must contain tagged bullets such as [MUST], [SHOULD], or [AVOID].")

    task_routing = top_level_section_body(stripped, "Task Routing") or ""
    if not re.search(r"^- To .+?:\s+\S", task_routing, re.MULTILINE):
        raise GuidanceMapError("Task Routing must contain bullets shaped like '- To <task>: ...'.")

    dependency_rules = top_level_section_body(stripped, "Module Dependency Rules") or ""
    if not re.search(r"^- \S", dependency_rules, re.MULTILINE):
        raise GuidanceMapError("Module Dependency Rules must contain at least one bullet.")

    module_map = top_level_section_body(stripped, "Module Map") or ""
    modules = module_entries(module_map)
    if not modules:
        raise GuidanceMapError("Module Map must contain at least one '#### <module name>' entry.")
    for module_name, module_body in modules:
        if not module_name:
            raise GuidanceMapError("Module Map contains an empty module heading.")
        for field in REQUIRED_MODULE_FIELDS:
            if not re.search(rf"^- {re.escape(field)}:\s*", module_body, re.MULTILINE):
                raise GuidanceMapError(f"Module '{module_name}' is missing required field: {field}.")


def render_block(guidance: str, timestamp: str, baseline: str, key_id: str, secret: bytes) -> str:
    if START_MARKER in guidance or END_MARKER in guidance:
        raise GuidanceMapError("Guidance content must not contain guidance block markers.")
    guidance = guidance.strip()
    if not guidance:
        raise GuidanceMapError("Guidance content is empty.")
    signature = compute_signature(secret, GENERATOR, GUIDE_FORMAT, timestamp, baseline, SIGNATURE_ALGORITHM, key_id, guidance)
    return "\n".join(
        [
            START_MARKER,
            "## Code Project Guidance Map",
            "",
            f"Generator: {GENERATOR}",
            f"Guide format: {GUIDE_FORMAT}",
            f"Generated at: {timestamp}",
            f"Git baseline: {baseline}",
            f"Signature key id: {key_id}",
            f"Signature algorithm: {SIGNATURE_ALGORITHM}",
            f"Signature: {signature}",
            "",
            guidance,
            END_MARKER,
            "",
        ]
    )


def update_agents_text(existing: str, block: str) -> str:
    found = find_block(existing)
    if found is None:
        prefix = existing.rstrip()
        if prefix:
            return f"{prefix}\n\n{block}"
        return block
    start, end, _ = found
    before = existing[:start].rstrip()
    after = existing[end:].lstrip()
    pieces = []
    if before:
        pieces.append(before)
    pieces.append(block.rstrip())
    if after:
        pieces.append(after.rstrip())
    return "\n\n".join(pieces) + "\n"


def status(repo_arg: Path) -> dict[str, object]:
    root, git_available = repo_root(repo_arg)
    agents_path = root / "AGENTS.md"
    exists = agents_path.exists()
    text = read_text(agents_path) if exists else ""
    block_info = find_block(text) if exists else None
    block = block_info[2] if block_info else None
    generated_at = metadata_value(GENERATED_AT_RE, block)
    generator = metadata_value(GENERATOR_RE, block)
    legacy_generated_by = metadata_value(LEGACY_GENERATED_BY_RE, block)
    guide_format = metadata_value(GUIDE_FORMAT_RE, block)
    git_baseline = metadata_value(GIT_BASELINE_RE, block)
    signature_key_id = metadata_value(SIGNATURE_KEY_ID_RE, block)
    signature_algorithm = metadata_value(SIGNATURE_ALGORITHM_RE, block)
    signature = metadata_value(SIGNATURE_RE, block)
    parsed_generated_at = parse_iso_datetime(generated_at)
    has_block = block is not None
    generated_at_valid = (not has_block and generated_at is None) or parsed_generated_at is not None
    guide_format_valid = (not has_block and guide_format is None) or guide_format == GUIDE_FORMAT
    signature_secret, signature_key_available, signature_key_source = load_signature_secret(signature_key_id, create=False)
    signature_valid = (
        signature_is_valid(
            block,
            generator,
            guide_format,
            generated_at,
            git_baseline,
            signature_algorithm,
            signature_key_id,
            signature,
            signature_secret,
        )
        if has_block
        else None
    )
    changes = changed_files(root, git_available, parsed_generated_at)

    return {
        "repo_root": str(root),
        "agents_path": str(agents_path),
        "agents_exists": exists,
        "has_block": has_block,
        "generator": generator,
        "generated_by": legacy_generated_by,
        "guide_format": guide_format,
        "guide_format_valid": guide_format_valid,
        "generated_at": generated_at,
        "generated_at_valid": generated_at_valid,
        "git_baseline": git_baseline,
        "signature_key_id": signature_key_id,
        "signature_key_available": signature_key_available if has_block else None,
        "signature_key_source": signature_key_source if has_block else None,
        "signature_algorithm": signature_algorithm,
        "signature": signature,
        "signature_valid": signature_valid,
        "git_available": git_available,
        "current_head": current_head(root, git_available),
        "changed_files": changes["all"],
        "changed_files_by_source": changes,
        "requires_full_read": (not has_block)
        or (has_block and (not guide_format_valid or not generated_at_valid or not signature_valid)),
    }


def verify(repo_arg: Path) -> dict[str, object]:
    current = status(repo_arg)
    changed = current["changed_files"]
    impact = classify_changed_files(changed if isinstance(changed, list) else [])
    reasons: list[str] = []
    recommended_action = "none"
    severity = "ok"

    if current["requires_full_read"]:
        recommended_action = "full_refresh"
        severity = "error"
        if not current["has_block"]:
            reasons.append("AGENTS.md guidance block is missing.")
        if current["has_block"] and not current["generated_at_valid"]:
            reasons.append("Generated at timestamp is missing or invalid.")
        if current["has_block"] and not current["guide_format_valid"]:
            reasons.append("Guide format is missing or unsupported.")
        if current["has_block"] and not current["signature_key_available"]:
            reasons.append("Signature key is unavailable; this block must be refreshed by the plugin or verified with the configured key.")
        if current["has_block"] and not current["signature_valid"]:
            reasons.append("Signature metadata is missing or invalid.")
    elif impact["boundary_rules"]:
        recommended_action = "refresh_dependency_rules"
        severity = "warning"
        reasons.append("Boundary-sensitive files changed; re-evaluate Agent Editing Rules and Module Dependency Rules.")
    elif impact["task_routing"]:
        recommended_action = "refresh_task_routing_and_affected_modules"
        severity = "warning"
        reasons.append("Task-routing files changed; refresh routing guidance and affected modules.")
    elif impact["module_internal"]:
        recommended_action = "refresh_affected_modules"
        severity = "warning"
        reasons.append("Module-internal code changed; refresh affected module entries.")
    elif impact["other"]:
        recommended_action = "review_changed_files"
        severity = "info"
        reasons.append("Unclassified files changed; review whether guidance should be refreshed.")
    elif impact["docs_only"]:
        severity = "info"
        reasons.append("Only documentation or CI files changed; guidance refresh is not required.")

    return {
        **current,
        "change_impact": impact,
        "stale": recommended_action not in {"none", "review_changed_files"},
        "severity": severity,
        "recommended_action": recommended_action,
        "reasons": reasons,
    }


def update(repo_arg: Path, guidance_file: Path, timestamp: str | None) -> dict[str, object]:
    root, git_available = repo_root(repo_arg)
    agents_path = root / "AGENTS.md"
    guidance = read_text(guidance_file)
    validate_guidance_shape(guidance)
    timestamp = timestamp or datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    baseline = current_head(root, git_available)
    existing = read_text(agents_path) if agents_path.exists() else ""
    existing_block_info = find_block(existing) if existing else None
    existing_block = existing_block_info[2] if existing_block_info else None
    key_id = metadata_value(SIGNATURE_KEY_ID_RE, existing_block) or default_signature_key_id(root, git_available)
    signature_secret, signature_key_available, signature_key_source = load_signature_secret(key_id, create=True)
    if not signature_key_available or signature_secret is None:
        raise GuidanceMapError("Unable to create or load the signature key.")
    block = render_block(guidance, timestamp, baseline, key_id, signature_secret)
    updated = update_agents_text(existing, block)
    write_text(agents_path, updated)
    return {
        "repo_root": str(root),
        "agents_path": str(agents_path),
        "has_block": True,
        "generated_at": timestamp,
        "git_baseline": baseline,
        "signature_key_id": key_id,
        "signature_key_source": signature_key_source,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Manage the AGENTS.md guidance map block.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    status_parser = subparsers.add_parser("status", help="Inspect AGENTS.md and Git delta state.")
    status_parser.add_argument("--repo", default=".", help="Repository or project directory.")

    verify_parser = subparsers.add_parser("verify", help="Classify guidance freshness for CI or local checks.")
    verify_parser.add_argument("--repo", default=".", help="Repository or project directory.")
    verify_parser.add_argument(
        "--fail-on",
        choices=("never", "stale", "error"),
        default="never",
        help="Exit with code 1 when the selected condition is met.",
    )

    update_parser = subparsers.add_parser("update", help="Create or replace the guidance block.")
    update_parser.add_argument("--repo", default=".", help="Repository or project directory.")
    update_parser.add_argument("--guidance-file", required=True, help="Markdown file containing module entries.")
    update_parser.add_argument("--timestamp", help="ISO-8601 timestamp override for tests.")

    args = parser.parse_args()
    try:
        if args.command == "status":
            output = status(Path(args.repo))
        elif args.command == "verify":
            output = verify(Path(args.repo))
        else:
            output = update(Path(args.repo), Path(args.guidance_file), args.timestamp)
    except GuidanceMapError as exc:
        print(json.dumps({"error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 2

    print(json.dumps(output, ensure_ascii=False, indent=2))
    if args.command == "verify":
        if args.fail_on == "error" and output["severity"] == "error":
            return 1
        if args.fail_on == "stale" and (output["stale"] or output["severity"] == "error"):
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
